// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsbn_bss.proto

package com.jsbn.protoc;

public final class protocol {
  private protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code jsbn.protoc.MSG}
   *
   * <pre>
   * 命令类型
   * </pre>
   */
  public enum MSG
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Heart_Beat = 0;</code>
     *
     * <pre>
     * 心跳
     * </pre>
     */
    Heart_Beat(0, 0),
    /**
     * <code>Login_Request = 4097;</code>
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    Login_Request(1, 4097),
    /**
     * <code>Login_Response = 4098;</code>
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    Login_Response(2, 4098),
    ;

    /**
     * <code>Heart_Beat = 0;</code>
     *
     * <pre>
     * 心跳
     * </pre>
     */
    public static final int Heart_Beat_VALUE = 0;
    /**
     * <code>Login_Request = 4097;</code>
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    public static final int Login_Request_VALUE = 4097;
    /**
     * <code>Login_Response = 4098;</code>
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    public static final int Login_Response_VALUE = 4098;


    public final int getNumber() { return value; }

    public static MSG valueOf(int value) {
      switch (value) {
        case 0: return Heart_Beat;
        case 4097: return Login_Request;
        case 4098: return Login_Response;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSG>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MSG>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSG>() {
            public MSG findValueByNumber(int number) {
              return MSG.valueOf(number);
            }
          };

    private final int value;

    private MSG(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jsbn.protoc.MSG)
  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsbn.protoc.LoginRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required bytes username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>required bytes username = 1;</code>
     */
    com.google.protobuf.ByteString getUsername();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code jsbn.protoc.LoginRequest}
   *
   * <pre>
   * 登录请求
   * </pre>
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:jsbn.protoc.LoginRequest)
      LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final LoginRequest defaultInstance;
    public static LoginRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<LoginRequest> PARSER =
        new com.google.protobuf.AbstractParser<LoginRequest>() {
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString username_;
    /**
     * <code>required bytes username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes username = 1;</code>
     */
    public com.google.protobuf.ByteString getUsername() {
      return username_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      username_ = com.google.protobuf.ByteString.EMPTY;
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, username_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, username_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsbn.protoc.protocol.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsbn.protoc.protocol.LoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code jsbn.protoc.LoginRequest}
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jsbn.protoc.protocol.LoginRequest, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:jsbn.protoc.LoginRequest)
        com.jsbn.protoc.protocol.LoginRequestOrBuilder {
      // Construct using com.jsbn.protoc.protocol.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jsbn.protoc.protocol.LoginRequest getDefaultInstanceForType() {
        return com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance();
      }

      public com.jsbn.protoc.protocol.LoginRequest build() {
        com.jsbn.protoc.protocol.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsbn.protoc.protocol.LoginRequest buildPartial() {
        com.jsbn.protoc.protocol.LoginRequest result = new com.jsbn.protoc.protocol.LoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jsbn.protoc.protocol.LoginRequest other) {
        if (other == com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsbn.protoc.protocol.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsbn.protoc.protocol.LoginRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString username_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes username = 1;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes username = 1;</code>
       */
      public com.google.protobuf.ByteString getUsername() {
        return username_;
      }
      /**
       * <code>required bytes username = 1;</code>
       */
      public Builder setUsername(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        
        return this;
      }
      /**
       * <code>required bytes username = 1;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jsbn.protoc.LoginRequest)
    }

    static {
      defaultInstance = new LoginRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jsbn.protoc.LoginRequest)
  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsbn.protoc.LoginResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required fixed32 result = 1;</code>
     *
     * <pre>
     * 应答结果
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required fixed32 result = 1;</code>
     *
     * <pre>
     * 应答结果
     * </pre>
     */
    int getResult();

    /**
     * <code>optional bytes error_description = 2;</code>
     *
     * <pre>
     * 应答结果描述
     * </pre>
     */
    boolean hasErrorDescription();
    /**
     * <code>optional bytes error_description = 2;</code>
     *
     * <pre>
     * 应答结果描述
     * </pre>
     */
    com.google.protobuf.ByteString getErrorDescription();
  }
  /**
   * Protobuf type {@code jsbn.protoc.LoginResponse}
   *
   * <pre>
   * 登录应答
   * </pre>
   */
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:jsbn.protoc.LoginResponse)
      LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginResponse(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final LoginResponse defaultInstance;
    public static LoginResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LoginResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              result_ = input.readFixed32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorDescription_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<LoginResponse> PARSER =
        new com.google.protobuf.AbstractParser<LoginResponse>() {
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>required fixed32 result = 1;</code>
     *
     * <pre>
     * 应答结果
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed32 result = 1;</code>
     *
     * <pre>
     * 应答结果
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    public static final int ERROR_DESCRIPTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString errorDescription_;
    /**
     * <code>optional bytes error_description = 2;</code>
     *
     * <pre>
     * 应答结果描述
     * </pre>
     */
    public boolean hasErrorDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes error_description = 2;</code>
     *
     * <pre>
     * 应答结果描述
     * </pre>
     */
    public com.google.protobuf.ByteString getErrorDescription() {
      return errorDescription_;
    }

    private void initFields() {
      result_ = 0;
      errorDescription_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, errorDescription_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, errorDescription_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsbn.protoc.protocol.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsbn.protoc.protocol.LoginResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code jsbn.protoc.LoginResponse}
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jsbn.protoc.protocol.LoginResponse, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:jsbn.protoc.LoginResponse)
        com.jsbn.protoc.protocol.LoginResponseOrBuilder {
      // Construct using com.jsbn.protoc.protocol.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorDescription_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jsbn.protoc.protocol.LoginResponse getDefaultInstanceForType() {
        return com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance();
      }

      public com.jsbn.protoc.protocol.LoginResponse build() {
        com.jsbn.protoc.protocol.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsbn.protoc.protocol.LoginResponse buildPartial() {
        com.jsbn.protoc.protocol.LoginResponse result = new com.jsbn.protoc.protocol.LoginResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorDescription_ = errorDescription_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jsbn.protoc.protocol.LoginResponse other) {
        if (other == com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasErrorDescription()) {
          setErrorDescription(other.getErrorDescription());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsbn.protoc.protocol.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsbn.protoc.protocol.LoginResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>required fixed32 result = 1;</code>
       *
       * <pre>
       * 应答结果
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed32 result = 1;</code>
       *
       * <pre>
       * 应答结果
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>required fixed32 result = 1;</code>
       *
       * <pre>
       * 应答结果
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        
        return this;
      }
      /**
       * <code>required fixed32 result = 1;</code>
       *
       * <pre>
       * 应答结果
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        
        return this;
      }

      private com.google.protobuf.ByteString errorDescription_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes error_description = 2;</code>
       *
       * <pre>
       * 应答结果描述
       * </pre>
       */
      public boolean hasErrorDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes error_description = 2;</code>
       *
       * <pre>
       * 应答结果描述
       * </pre>
       */
      public com.google.protobuf.ByteString getErrorDescription() {
        return errorDescription_;
      }
      /**
       * <code>optional bytes error_description = 2;</code>
       *
       * <pre>
       * 应答结果描述
       * </pre>
       */
      public Builder setErrorDescription(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorDescription_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes error_description = 2;</code>
       *
       * <pre>
       * 应答结果描述
       * </pre>
       */
      public Builder clearErrorDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorDescription_ = getDefaultInstance().getErrorDescription();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jsbn.protoc.LoginResponse)
    }

    static {
      defaultInstance = new LoginResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jsbn.protoc.LoginResponse)
  }

  public interface BSSNetProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jsbn.protoc.BSSNetProtocol)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .jsbn.protoc.MSG type = 1;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .jsbn.protoc.MSG type = 1;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    com.jsbn.protoc.protocol.MSG getType();

    /**
     * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    boolean hasLoginrequest();
    /**
     * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    com.jsbn.protoc.protocol.LoginRequest getLoginrequest();

    /**
     * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    boolean hasLoginresponse();
    /**
     * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    com.jsbn.protoc.protocol.LoginResponse getLoginresponse();
  }
  /**
   * Protobuf type {@code jsbn.protoc.BSSNetProtocol}
   *
   * <pre>
   * 传输通信协议
   * </pre>
   */
  public static final class BSSNetProtocol extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:jsbn.protoc.BSSNetProtocol)
      BSSNetProtocolOrBuilder {
    // Use BSSNetProtocol.newBuilder() to construct.
    private BSSNetProtocol(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BSSNetProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final BSSNetProtocol defaultInstance;
    public static BSSNetProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public BSSNetProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private BSSNetProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.jsbn.protoc.protocol.MSG value = com.jsbn.protoc.protocol.MSG.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 26: {
              com.jsbn.protoc.protocol.LoginRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = loginrequest_.toBuilder();
              }
              loginrequest_ = input.readMessage(com.jsbn.protoc.protocol.LoginRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginrequest_);
                loginrequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              com.jsbn.protoc.protocol.LoginResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = loginresponse_.toBuilder();
              }
              loginresponse_ = input.readMessage(com.jsbn.protoc.protocol.LoginResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginresponse_);
                loginresponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<BSSNetProtocol> PARSER =
        new com.google.protobuf.AbstractParser<BSSNetProtocol>() {
      public BSSNetProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BSSNetProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BSSNetProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.jsbn.protoc.protocol.MSG type_;
    /**
     * <code>required .jsbn.protoc.MSG type = 1;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .jsbn.protoc.MSG type = 1;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public com.jsbn.protoc.protocol.MSG getType() {
      return type_;
    }

    public static final int LOGINREQUEST_FIELD_NUMBER = 3;
    private com.jsbn.protoc.protocol.LoginRequest loginrequest_;
    /**
     * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    public boolean hasLoginrequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
     *
     * <pre>
     * 登录请求
     * </pre>
     */
    public com.jsbn.protoc.protocol.LoginRequest getLoginrequest() {
      return loginrequest_;
    }

    public static final int LOGINRESPONSE_FIELD_NUMBER = 4;
    private com.jsbn.protoc.protocol.LoginResponse loginresponse_;
    /**
     * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    public boolean hasLoginresponse() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
     *
     * <pre>
     * 登录应答
     * </pre>
     */
    public com.jsbn.protoc.protocol.LoginResponse getLoginresponse() {
      return loginresponse_;
    }

    private void initFields() {
      type_ = com.jsbn.protoc.protocol.MSG.Heart_Beat;
      loginrequest_ = com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance();
      loginresponse_ = com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLoginrequest()) {
        if (!getLoginrequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasLoginresponse()) {
        if (!getLoginresponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, loginrequest_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, loginresponse_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, loginrequest_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, loginresponse_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jsbn.protoc.protocol.BSSNetProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jsbn.protoc.protocol.BSSNetProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code jsbn.protoc.BSSNetProtocol}
     *
     * <pre>
     * 传输通信协议
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jsbn.protoc.protocol.BSSNetProtocol, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:jsbn.protoc.BSSNetProtocol)
        com.jsbn.protoc.protocol.BSSNetProtocolOrBuilder {
      // Construct using com.jsbn.protoc.protocol.BSSNetProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.jsbn.protoc.protocol.MSG.Heart_Beat;
        bitField0_ = (bitField0_ & ~0x00000001);
        loginrequest_ = com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        loginresponse_ = com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jsbn.protoc.protocol.BSSNetProtocol getDefaultInstanceForType() {
        return com.jsbn.protoc.protocol.BSSNetProtocol.getDefaultInstance();
      }

      public com.jsbn.protoc.protocol.BSSNetProtocol build() {
        com.jsbn.protoc.protocol.BSSNetProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jsbn.protoc.protocol.BSSNetProtocol buildPartial() {
        com.jsbn.protoc.protocol.BSSNetProtocol result = new com.jsbn.protoc.protocol.BSSNetProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginrequest_ = loginrequest_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.loginresponse_ = loginresponse_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jsbn.protoc.protocol.BSSNetProtocol other) {
        if (other == com.jsbn.protoc.protocol.BSSNetProtocol.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLoginrequest()) {
          mergeLoginrequest(other.getLoginrequest());
        }
        if (other.hasLoginresponse()) {
          mergeLoginresponse(other.getLoginresponse());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasLoginrequest()) {
          if (!getLoginrequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasLoginresponse()) {
          if (!getLoginresponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jsbn.protoc.protocol.BSSNetProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jsbn.protoc.protocol.BSSNetProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.jsbn.protoc.protocol.MSG type_ = com.jsbn.protoc.protocol.MSG.Heart_Beat;
      /**
       * <code>required .jsbn.protoc.MSG type = 1;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .jsbn.protoc.MSG type = 1;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public com.jsbn.protoc.protocol.MSG getType() {
        return type_;
      }
      /**
       * <code>required .jsbn.protoc.MSG type = 1;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder setType(com.jsbn.protoc.protocol.MSG value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        
        return this;
      }
      /**
       * <code>required .jsbn.protoc.MSG type = 1;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.jsbn.protoc.protocol.MSG.Heart_Beat;
        
        return this;
      }

      private com.jsbn.protoc.protocol.LoginRequest loginrequest_ = com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance();
      /**
       * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
       *
       * <pre>
       * 登录请求
       * </pre>
       */
      public boolean hasLoginrequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
       *
       * <pre>
       * 登录请求
       * </pre>
       */
      public com.jsbn.protoc.protocol.LoginRequest getLoginrequest() {
        return loginrequest_;
      }
      /**
       * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
       *
       * <pre>
       * 登录请求
       * </pre>
       */
      public Builder setLoginrequest(com.jsbn.protoc.protocol.LoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginrequest_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
       *
       * <pre>
       * 登录请求
       * </pre>
       */
      public Builder setLoginrequest(
          com.jsbn.protoc.protocol.LoginRequest.Builder builderForValue) {
        loginrequest_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
       *
       * <pre>
       * 登录请求
       * </pre>
       */
      public Builder mergeLoginrequest(com.jsbn.protoc.protocol.LoginRequest value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            loginrequest_ != com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance()) {
          loginrequest_ =
            com.jsbn.protoc.protocol.LoginRequest.newBuilder(loginrequest_).mergeFrom(value).buildPartial();
        } else {
          loginrequest_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .jsbn.protoc.LoginRequest loginrequest = 3;</code>
       *
       * <pre>
       * 登录请求
       * </pre>
       */
      public Builder clearLoginrequest() {
        loginrequest_ = com.jsbn.protoc.protocol.LoginRequest.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      private com.jsbn.protoc.protocol.LoginResponse loginresponse_ = com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance();
      /**
       * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
       *
       * <pre>
       * 登录应答
       * </pre>
       */
      public boolean hasLoginresponse() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
       *
       * <pre>
       * 登录应答
       * </pre>
       */
      public com.jsbn.protoc.protocol.LoginResponse getLoginresponse() {
        return loginresponse_;
      }
      /**
       * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
       *
       * <pre>
       * 登录应答
       * </pre>
       */
      public Builder setLoginresponse(com.jsbn.protoc.protocol.LoginResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginresponse_ = value;

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
       *
       * <pre>
       * 登录应答
       * </pre>
       */
      public Builder setLoginresponse(
          com.jsbn.protoc.protocol.LoginResponse.Builder builderForValue) {
        loginresponse_ = builderForValue.build();

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
       *
       * <pre>
       * 登录应答
       * </pre>
       */
      public Builder mergeLoginresponse(com.jsbn.protoc.protocol.LoginResponse value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            loginresponse_ != com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance()) {
          loginresponse_ =
            com.jsbn.protoc.protocol.LoginResponse.newBuilder(loginresponse_).mergeFrom(value).buildPartial();
        } else {
          loginresponse_ = value;
        }

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .jsbn.protoc.LoginResponse loginresponse = 4;</code>
       *
       * <pre>
       * 登录应答
       * </pre>
       */
      public Builder clearLoginresponse() {
        loginresponse_ = com.jsbn.protoc.protocol.LoginResponse.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jsbn.protoc.BSSNetProtocol)
    }

    static {
      defaultInstance = new BSSNetProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jsbn.protoc.BSSNetProtocol)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
